#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: launch <name>"
  exit 1
fi

DROPLET_NAME=$1
DROPLET_SIZEID=66
DROPLET_IMAGEID=365680 # centos 6.4 x64
DROPLET_REGIONID=2

tugboat info $DROPLET_NAME

DROPLET_EXISTS=$?
set -e

if [ $DROPLET_EXISTS -ne 0 ]
	then
	tugboat create $DROPLET_NAME -s $DROPLET_SIZEID -i $DROPLET_IMAGEID -r $DROPLET_REGIONID -k $DIGITAL_OCEAN_SSH
fi

tugboat wait $DROPLET_NAME

IP=`tugboat info $DROPLET_NAME | grep IP | awk '{ print $2 }'`
echo "$DROPLET_NAME is launched on $IP"

if [ $DROPLET_EXISTS -ne 0 ]
	then
	ssh-keygen -R $IP

	sleep 5
	ssh root@$IP "/usr/bin/yum -y update"
	ssh root@$IP "/usr/bin/yum -y update"
	ssh root@$IP "/bin/rpm -ivh http://yum.puppetlabs.com/el/6/products/i386/puppetlabs-release-6-7.noarch.rpm"
	ssh root@$IP "/usr/bin/yum -y install puppet"
	ssh root@$IP "/usr/bin/puppet module install maestrodev/wget"
	ssh root@$IP "/bin/mkdir -p /plans"
fi

scp ./plans/standard.pp root@$IP:/plans/standard.pp
ssh root@$IP "puppet apply /plans/standard.pp"

tugboat info $DROPLET_NAME