#!/bin/bash

if [ $# -ne 2 ]
then
  echo "Usage: launch <name> <type>"
  exit 1
fi

DROPLET_NAME=$1
DROPLET_SIZEID=66
DROPLET_REGIONID=1
SHIP_TYPE=$2

if [ ! -d "./plans/$SHIP_TYPE" ]; then
  echo "Cannot find plans for $SHIP_TYPE"
  exit 1
fi

source "./plans/$SHIP_TYPE/plan.cfg"

tugboat info $DROPLET_NAME

DROPLET_EXISTS=$?
set -e

# create droplet if it doesn't exist
if [ $DROPLET_EXISTS -ne 0 ]
	then
	tugboat create $DROPLET_NAME -s $DROPLET_SIZEID -i $DROPLET_IMAGEID -r $DROPLET_REGIONID -k $DIGITAL_OCEAN_SSH
fi

# wait for active
tugboat wait $DROPLET_NAME

# work out ipaddress
IP=`tugboat info $DROPLET_NAME | grep IP | awk '{ print $2 }'`
echo "$DROPLET_NAME is launched on $IP"

if [ $DROPLET_EXISTS -ne 0 ]
	then
	# remove old ipaddress from known hosts as it's probably changed ?
	ssh-keygen -R $IP 
fi

# copy plans
ssh root@$IP "/bin/mkdir -p /plans"
pushd "./plans/$SHIP_TYPE"
scp -r "." root@$IP:/plans
popd

# bootstrap
ssh root@$IP $BOOTSTRAP_COMMAND

# finished
tugboat info $DROPLET_NAME
